### ISSUE TITLE
Directory for report not generated

### ISSUE THREAD

**Issue by duggiemitchell** [kalbeekatz/storybook-a11y-report#13]
**What behavior were you expecting?**

When running `npx storybook-a11y-report` I expect a new `__report__` directory created with the report in a markdown file.  

**What actually happened?**

No directory or file was created.

**How can I reproduce it?**

1. make sure storybook is running on localhost:6060
2. in the terminal run `npx storybook-a11y-report`

**What was your environment like?**

`package.json`
```json
  "scripts": {
    ...
    "a11y-report": "npx storybook-a11y-report",
    "a11y-report:ci": "npx storybook-a11y-report --exit",
    "lint": "tsdx lint",
    "prepare": "tsdx build",
    "size": "size-limit",
    "analyze": "size-limit --why",
    "storybook:start": "start-storybook -p 6006",
    "storybook:build": "build-storybook",
    ...
  },
  ...
  "devDependencies": {
    ...
    "@storybook/addon-a11y": "^6.2.7",
    "@storybook/addon-controls": "^6.2.7",
    "storybook-a11y-report": "^0.0.11",
    "@storybook/addon-essentials": "^6.2.7",
    "@storybook/addon-info": "^5.3.21",
    "@storybook/addon-links": "^6.2.7",
    "@storybook/addons": "^6.2.7",
    "@storybook/react": "^6.2.7",
    ...
  },
```
`.storybook/main.js`
```js
module.exports = {
  ...
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-controls',
    '@storybook/addon-a11y',
  ],
  ...
};
```
**Do you have any logs?**

```bash
erica@erica-xps:~/Projects/Greyshore/app-prometric-design-system$ yarn a11y-report
yarn run v1.22.4
$ npx storybook-a11y-report
✔ Found 1 stories.


✨ ✨ That's perfect, there is no a11y violation! ✨ ✨
Done in 2.60s.
```

**Comment by kalbeekatz** [comment]
Thanks for reporting.

In your logs,

> ✨ ✨ That's perfect, there is no a11y violation! ✨ ✨

This log means that there are no violations in the Storybook.

storybook-a11y-addon creates a `__report__` directory only if there are violations in the Storybook.

Please also check below.
If you use npx, you can run it in any directory, but create a `__report__` in the directory where you run it.
