### ISSUE TITLE
Using "--exit" option always fails even if there are no violations

### ISSUE THREAD

**Issue by dibimer** [kalbeekatz/storybook-a11y-report#48]
Starting from version 0.0.15 the usage of the "--exit" option seems to be broken as report creation will always return exit code 1.

The behaviour has been introduced with https://github.com/kalbeekatz/storybook-a11y-report/commit/b6a6d1937a977e726ce839cfdbf029933d7e63e9

The condition https://github.com/kalbeekatz/storybook-a11y-report/blob/1787c802b51ca4e9da175eb74842a38f73edeb17/src/index.ts#L181 is currently always true as the "header" has been moved into the _report_ variable. Therefore if the exit option is used https://github.com/kalbeekatz/storybook-a11y-report/blob/1787c802b51ca4e9da175eb74842a38f73edeb17/src/index.ts#L192 will be called.

Expected behaviour: "--exit" option should only have non 0 exit code if violations are found.

**Comment by kalbeekatz** [comment]
@dibimer Thanks for reporting.

I fixed this issue v0.0.18.
I hope you continue to use story-a11y-report.

**Comment by dbirzer** [comment]
@kalbeekatz thank you for fixing the issue so quickly.

**Comment by dibimer** [comment]
@kalbeekatz Thank you for fixing the issue so quickly.
